#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include "vecmat.h"

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void MainFormClose(wxCloseEvent& event);
		void WxPanel_Paint(wxPaintEvent& event);
		void WxPanel_Repaint( wxUpdateUIEvent& event );
		void m_button_load_geometry_click( wxCommandEvent& event );
		void Scrolls_Updated( wxScrollEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
  void Repaint(wxDC& dc);

	double observerZ;

	Matrix4 Translate(double dx, double dy, double dz);
	Matrix4 RotateX(double alpha);
	Matrix4 RotateY(double alpha);
	Matrix4 RotateZ(double alpha);
	Matrix4 Scale(double Sx, double Sy, double Sz);
	Matrix4 FlipY();
	Matrix4 Perspective();

	void Normalize(Vector4& point);

	bool IsBehindClipPlane(Vector4 point);
	bool Clip(Vector4& start, Vector4& end);
};

#endif // __GUIMyFrame1__
