#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/timer.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_buttonLoadFileOnButtonClick( wxCommandEvent& event );
		void m_buttonCensorshipOnButtonClick( wxCommandEvent& event );
		void m_buttonErodeOnButtonClick( wxCommandEvent& event );
		void m_checkBoxAnimationOnCheckBox( wxCommandEvent& event );
		void m_panel_imageOnPaint( wxPaintEvent& event );
		void m_panel_imageOnUpdateUI( wxUpdateUIEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members


	wxImage img_org, img_cpy;
	bool hasAnimBeenGenerated;
	std::array<wxBitmap, 60> anim_frames;
	unsigned int frame_no;

	wxTimer timer;
	void OnTimer(wxTimerEvent& event);
	~GUIMyFrame1();
};

#endif // __GUIMyFrame1__
